In [1]:
import numpy as np
W = np . array ([[0 , 1 , 0 , 1] ,
                 [0 , 1 , 0 , 0] ,
                 [1 , 0 , 0 , 0] ,
                 [0 , 0 , 1 , 0]] , dtype = bool )
n = len( W )
for k in range ( n ) :
    for i in range ( n ) :
        for j in range ( n ) :
            W [i , j ] += W [i , k ] * W [k , j ]
    print ( k +1 , np . array (W , dtype = int) )

1 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]]
2 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]]
3 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [1 1 1 1]]
4 [[1 1 1 1]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 1 1]]
